### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by MacDada** [airbnb/infinity#50]
Last merged commit was a year ago, the repository has 8 pull requests and ~~35~~ 36 issues.

I'd like to use `infinity` in my project, but I'm not sure it's a good idea, considering it does not have any kind of support anymore…

**Comment by andrewtweber** [comment]
Ironic that now iScroll has also had no updates since September 2014 (shortly before the last comment in this thread)

**Comment by yairEO** [comment]
I have created my own, super light-weight, never-disappointing infinite loader after the internet disappointed me with one:

https://github.com/yairEO/infinite

**Comment by ljharb** [comment]
This project is no longer maintained, and is deprecated.
