### ISSUE TITLE
SSL error on https://airbnb.io/infinity

### ISSUE THREAD

**Issue by dominikwilkowski** [airbnb/infinity#58]
<img width="271" alt="screen shot 2016-05-09 at 9 37 33 am" src="https://cloud.githubusercontent.com/assets/1266923/15101074/bca088b2-15c9-11e6-98f7-d2dad7ed2469.png">

Didn't have time to test why, sorry.

**Comment by ljharb** [comment]
It's because Github Pages doesn't support SSL with custom domains. Where did you see an HTTPS link to it?

**Comment by dominikwilkowski** [comment]
I clicked on your URL of your repo:
http://airbnb.github.com/infinity

<img width="540" alt="screen shot 2016-05-09 at 12 15 17 pm" src="https://cloud.githubusercontent.com/assets/1266923/15102205/c817bc04-15df-11e6-9cbe-0ca3d018980e.png">

**Comment by ljharb** [comment]
ah yes, i guess github's own redirect is broken :-) thanks, I'll fix the URL.
