### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by caseybaggz** [airbnb/infinity#61]
Noticed that most of the issues are pretty old. Are you guys still maintaining this or is it frozen?

**Comment by caseybaggz** [comment]
Wow. just read the README....I'm a n00b.

**Comment by ljharb** [comment]
No - see the comment in the readme, as well as "deprecated" in the repo tagline (added in 8bd1f9608bd3239a41831f37bfc2a969e22ec457).

(Infinite scroll is often a problematic UX pattern, so I wouldn't recommend it personally anyways)
