### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by x09326** [airbnb/infinity#62]
Hi, I want to confirm whether the license is **BSD-3-Clause**.
Because it looks a little different from the **BSD-3-Clause** license.
https://github.com/cdnjs/cdnjs/pull/9960

**Comment by ljharb** [comment]
This project is deprecated and no longer maintained, so whatever license it has is the one it will keep.

https://github.com/airbnb/infinity/commits/master/LICENSE is the history - perhaps the original matches bsd 3-clause? If so, the addition of the extra sentence wouldn't change its license type.

**Comment by x09326** [comment]
Okay, thanks for your response. :+1:
